global:
  scrape_interval: 2s

scrape_configs:
  - job_name: 'quarkus'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['flight-service:8080', 'passenger-service:8080', 'baggage-service:8080']
        labels:
          group: 'quarkus-apps'
